# Generated by Django 4.0.4 on 2022-04-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='application_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
    ]
